#
# Application URLS
#

development:
  cas_url: "https://aztec.ncgr.org:7777"
  cas_validate: "https://aztec.ncgr.org:7777/proxyValidate"

production:
  cas_url: "https://cas.comparative-legumes.org"
  cas_validate: "https://velarde.ncgr.org:8055/proxyValidate"

test:
  cas_url: "https://silicon.ncgr.org:7777"
  cas_validate: "https://silicon.ncgr.org:7777/proxyValidate"

